version: '3'
services:
  database:
    image: mysql:8.0.33-oracle
    container_name: Fundy-DB
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fundy
      - TZ="Asia/Seoul"
    ports:
      - "3308:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    stdin_open: true # `-i`
    tty: true # `-t`

  redis:
    image: redis:latest
    container_name: Fundy-Cache
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis.conf:/usr/local/conf/redis.conf

  application:
    image: openjdk:17-ea-33-jdk-buster
    container_name: Fundy-Server
    volumes:
      - ./gradle:/gradle
      - ./build.gradle:/build.gradle
      - ./gradlew:/gradlew
      - ./src:/src
      - ./run-app.sh:/run-app.sh
    stdin_open: true # `-i`
    tty: true # `-t`
    ports:
      - "8080:8080"

    # application.yml 파일의 내용을 무시하고 해당 환경 변수로 설정해서 실행합니다.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/fundy?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    command: /bin/bash /run-app.sh
    depends_on:
      - database
      - redis


